### PR TITLE
[IMP] coexist with crm

### PR DESCRIPTION
**Pull request by hbrunn**
fixes #283

### CODE REVIEW

**Comment by thomaspaulb** [comment]
I merged this with the enhancements from `partner_merge_svg` and tried to install it. By itself the module works fine, but then when coexisting with crm, trouble starts:

- The `crm` models are chosen and ours are deleted, however the enhancements I made on `res.partner` are also deleted
- The `crm` XML is chosen and ours is not loaded. I have added a field on the new XML, but then that is deleted too. To do it properly I should create a separate XML that is always loaded and inherits from either the one from crm or the one from here, but there we have an either/or conundrum again.

I think I could solve both of those problems by deleting only exactly that which is double, and then renaming whatever comes from crm as if to come from base_partner_merge, although it's pretty heavy stuff to wrap the mind around, also for future coders.

If we are to enhance the deduplication functionality anyway, we might as well create a more solid, easier-extendible, code-reviewed foundation for it and discard the code that ships with Odoo, instead of frantically trying to reuse it... then create a glue module that depends on CRM which then hides/deletes the existing menu item. I can't really judge whether that is butchery or the smarter thing to do.

**Comment by hbrunn** [comment]
well, the problem with our code-reviewed copy earlier was that there were a couple of fixes we missed, one which caused nasty data loss. So I think doing this dance is worth the time. Can you do your changes in another file indeed, and for enhancing the code, do an override of the model (so just standard inheritance)? Then your overrides should be loaded, your xml file anyways, and we have achieved an interesting technical solution :-)
Maybe add some comments to make it simpler for future coders to wrap their minds around?

**Comment by thomaspaulb** [comment]
Something I can't wrap my head around just yet, is how to solve the fact that when `base_partner_merge` is already installed, and you want to install `crm` also, the following is raised:

`Cannot create a consistent method resolution order (MRO) for bases ResPartner, res.partner`

For now am working around it by deinstalling `base_partner_merge` and then installing `crm` before reinstalling `base_partner_merge` again, but later should come back to this.

**Comment by thomaspaulb** [comment]
Closing this and continuing here: https://github.com/OCA/partner-contact/pull/406

**Pull request merged**
